name: Deploy Collector

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzmq3-dev
      
      - name: Build
        run: |
          cd src/collector
          go mod tidy
          # Use CGO with dynamic linking
          CGO_ENABLED=1 go build -o collector
      
      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp src/collector/collector deploy/
          cp src/collector/config.yaml deploy/
          chmod +x deploy/collector
          
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
          
      - name: Prepare remote directory and fix permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Create directory if it doesn't exist
            sudo mkdir -p /opt/quake-stats
            # Create a temporary directory with proper permissions
            mkdir -p ~/quake-stats-temp
            
            # Fix broken dependencies and install required libraries
            sudo apt-get update
            sudo apt --fix-broken install -y
            sudo apt-get install -y libzmq5 libstdc++6 libnorm1 libpgm-5.3-0
          
      - name: Copy files to VM using SCP
        run: |
          # Copy to user's home directory first (where we know we have permissions)
          scp -i ~/.ssh/deploy_key -r deploy/* ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:~/quake-stats-temp/
      
      - name: Move files and set up service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Move files to destination with sudo
            sudo cp -R ~/quake-stats-temp/* /opt/quake-stats/
            # Set proper ownership and permissions
            sudo chown -R ${{ secrets.VM_USERNAME }}:${{ secrets.VM_USERNAME }} /opt/quake-stats
            sudo chmod -R 755 /opt/quake-stats
            sudo chmod +x /opt/quake-stats/collector
            
            cd /opt/quake-stats
            
            # Set up systemd service
            cat > /tmp/quake-collector.service << EOF
            [Unit]
            Description=Quake Stats Collector
            After=network.target
            
            [Service]
            Type=simple
            User=${{ secrets.VM_USERNAME }}
            WorkingDirectory=/opt/quake-stats
            ExecStart=/opt/quake-stats/collector
            Restart=always
            RestartSec=10
            
            # Environment variables
            Environment="ZMQ_ENDPOINT=${{ secrets.ZMQ_ENDPOINT }}"
            # Make sure system libraries are available
            Environment="LD_LIBRARY_PATH=/usr/lib:/usr/local/lib"
            
            [Install]
            WantedBy=multi-user.target
            EOF
            
            # Check library dependencies
            ldd /opt/quake-stats/collector
            
            # Install and start service
            sudo mv /tmp/quake-collector.service /etc/systemd/system/quake-collector.service
            sudo systemctl daemon-reload
            sudo systemctl enable quake-collector
            sudo systemctl restart quake-collector
            
            # Show status
            sleep 2
            sudo systemctl status quake-collector
            
            # Clean up temp directory
            rm -rf ~/quake-stats-temp
            
            echo "Service installed and running. Use these commands to manage it:"
            echo "- View logs: sudo journalctl -u quake-collector -f"
            echo "- Stop service: sudo systemctl stop quake-collector"
            echo "- Start service: sudo systemctl start quake-collector"
            echo "- Restart service: sudo systemctl restart quake-collector" 