name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzmq3-dev
      
      - name: Build and Test
        run: |
          cd src/collector
          go mod tidy
          go build -o collector
          go test -v ./...
          
  # This is a required job that deployment depends on, ensuring tests run first
  check:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Tests Passed
        run: echo "All tests passed!" 